# Copyright (C) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/test.gni")

ohos_unittest("caller_info_query_extension_test") {
  install_enable = true
  subsystem_name = "telephony"
  part_name = "number_identity"
  test_module = "NumberIdentity"
  test_suite = "caller_info_query_extension_test"
  module_out_path = part_name + "/" + test_module + "/" + test_suite
  sources = [
    "napi_helper/src/napi_helper_test.cpp",
    "core/caller_info_query_extension_module_loader_test.cpp",
    "core/caller_info_query_stub_test.cpp",
    "//vendor/huawei/base/telephony/call_enhanced/number_identity/frameworks/extension/core/src/caller_info_query_extension_module_loader.cpp"
  ]

  deps = [
    "//vendor/huawei/base/telephony/call_enhanced/number_identity/frameworks/extension:caller_info_query_extension",
  ]

  include_dirs = [
    "//vendor/huawei/base/telephony/call_enhanced/number_identity/frameworks/extension/napi_helper/include",
    "//vendor/huawei/base/telephony/call_enhanced/number_identity/frameworks/extension/core/include"
  ]

  external_deps = [
    "ability_base:base",
    "ability_base:want",
    "ability_base:zuri",
    "ability_runtime:ability_manager",
    "ability_runtime:abilitykit_native",
    "ability_runtime:app_context",
    "ability_runtime:data_ability_helper",
    "ability_runtime:dataobs_manager",
    "ability_runtime:napi_base_context",
    "ability_runtime:wantagent_innerkits",
    "ability_runtime:ability_context_native",
    "common_event_service:cesfwk_innerkits",
    "c_utils:utils",
    "data_share:datashare_common",
    "data_share:datashare_consumer",
    "data_share:datashare_provider",
    "eventhandler:libeventhandler",
    "hilog:libhilog",
    "i18n:intl_util",
    "init:libbegetutil",
    "ipc:ipc_single",
    "kv_store:distributeddata_inner",
    "napi:ace_napi",
    "googletest:gtest_main"
  ]

  defines = [
    "NUMBERLOCATION_LOG_TAG = \"CallerInfoQueryExtensionTest\"",
    "LOG_DOMAIN = 0xD001F10",
    "NUMBER_IDENTITY_DEBUG",
  ]
}
